# Use Node.js 20 as the base image
FROM node:20.16.0-slim

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy source code
COPY . .

# Run the application
CMD ["node", "src/bench.js"] 